apiVersion: v1
kind: Secret
metadata:
  name: aipass-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: jdbc:postgresql://postgres-service:5432/aipass
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  WEBHOOK_SECRET: aipass-livesync-secret-2026
