apiVersion: v1
kind: Service
metadata:
  name: aipass-backend-service
  namespace: default
spec:
  selector:
    app: aipass-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
